### ISSUE TITLE
INSTALL LINUX

### ISSUE THREAD

**Issue by iAmG-r00t** [codekitchen/pipeline#15]
I know this is a dummy question, but is there a way to install it like with apt on a wget bash script other than from the source?

Regards,

gr00t

**Comment by codekitchen** [comment]
Not currently, sorry, I really do need to at least apt package it or something. I'd love help with that as I only have a little experience there.

**Comment by iAmG-r00t** [comment]
Okay, let me try and see how to work on this then post it here. Mostly by the end of this week 😄

**Comment by codekitchen** [comment]
Awesome! I did look into packaging it as a snap a while back, since that seems to be gaining traction as a cross-distro packaging format, but after some reading and experimenting it didn't seem like a good fit. Snaps are supposed to be sandboxed and since pipeline is basically a wrapper around your shell, it needs access to everything your shell can access.

**Comment by iAmG-r00t** [comment]
Hey, so I wasn't able to find a way to package it to snap, but I was able to find a way to use docker, I have raised a PR #16. Check it out it works on my end really smoothly.

Thanks alot for your tool 😀 and happy holidays 🎅.
